en:
  dry_validation:
    errors:
      invalid_key_type: all keys need to be of type String
      invalid_value_type: all values need to be of type String
      max_payload_size: is more than `max_payload_size` config value
