en:
  errors:
    broker_schema?: >
      has an invalid format.
      Expected schema, host and port number.
      Example: kafka://127.0.0.1:9092 or kafka+ssl://127.0.0.1:9092
    ssl_client_cert_with_ssl_client_cert_key: >
      Both ssl_client_cert and ssl_client_cert_key need to be provided.
    ssl_client_cert_key_with_ssl_client_cert: >
      Both ssl_client_cert_key and ssl_client_cert need to be provided.
    ssl_client_cert_chain_with_ssl_client_cert: >
      Both ssl_client_cert_chain and ssl_client_cert need to be provided.
    ssl_client_cert_chain_with_ssl_client_cert_key: >
      Both ssl_client_cert_chain and ssl_client_cert_key need to be provided.
    ssl_client_cert_key_password_with_ssl_client_cert_key: >
      Both ssl_client_cert_key_password and ssl_client_cert_key need to be provided.
    sasl_oauth_token_provider_respond_to_token: >
      sasl_oauth_token_provider needs to respond to a #token method.
